MIAN_MODULE := hello_lm32_world.c
SOURCE += $(SCU_LIB_SRC_LM32_DIR)/scu_std_init.c
# NO_LTO := 1
CODE_OPTIMIZATION = s
REPOSITORY_DIR := $(shell git rev-parse --show-toplevel)
include $(REPOSITORY_DIR)/makefiles/makefile.scu
#=================================== EOF ======================================
