MIAN_MODULE := wr_time_test.c



CODE_OPTIMIZATION = s

# TOOLCHAIN_DIR = $(INCLUDED_TOOLCHAIN_DIR)

REPOSITORY_DIR := $(shell git rev-parse --show-toplevel)
include $(REPOSITORY_DIR)/makefiles/makefile.scu
#=================================== EOF ======================================

