MIAN_MODULE := asm_test.c
SOURCE += $(SCU_LIB_SRC_LM32_DIR)/scu_std_init.c
REPOSITORY_DIR := $(shell git rev-parse --show-toplevel)

CODE_OPTIMIZATION = s
NO_LTO=1

include $(REPOSITORY_DIR)/makefiles/makefile.scu
#=================================== EOF ======================================

