
MIAN_MODULE := cpptest.cpp



SOURCE += $(SCU_LIB_SRC_DIR)/dow_crc.c

CODE_OPTIMIZATION = s

REPOSITORY_DIR := $(shell git rev-parse --show-toplevel)
include $(REPOSITORY_DIR)/makefiles/makefile.scu
