###############################################################################
##                                                                           ##
##             Makefile LM32 FG software scu3_control.bin                    ##
##                                                                           ##
##---------------------------------------------------------------------------##
## File:    SCU3/Makefile                                                    ##
## (c):     GSI Helmholtz Centre for Heavy Ion Research GmbH                 ##
## Author:  Ulrich Becker                                                    ##
## Date:    12.10.2023                                                       ##
###############################################################################
BASE_VERSION = 4
SUB_VERSION  = 5.4
TARGET       := scu3_control

BASE_DIR = $(shell pwd)/..


include $(BASE_DIR)/scu_control.mk

#=================================== EOF ======================================
