MIAN_MODULE := scu_bus_test.c

REPOSITORY_DIR := $(shell git rev-parse --show-toplevel)

SOURCE += $(SCU_LIB_SRC_LM32_DIR)/scu_bus.c

DEFINES += CONFIG_SCU_BUS_PEDANTIC_CHECK

include $(REPOSITORY_DIR)/makefiles/makefile.scu
#=================================== EOF ======================================

